"""
Django settings for wingastock project.

Generated by 'django-admin startproject' using Django 6.0.6.
"""

from pathlib import Path
import os

from dotenv import load_dotenv


# ==========================================================
# BASE DIRECTORY
# ==========================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# Load .env file
load_dotenv(BASE_DIR / ".env")



# ==========================================================
# SECURITY
# ==========================================================

SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-change-this-in-production"
)

DEBUG = True

ALLOWED_HOSTS = ["*"]


# ==========================================================
# APPLICATIONS
# ==========================================================

INSTALLED_APPS = [

    # Django applications
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'django.contrib.humanize',
    "django.contrib.sitemaps",

    # Cloudinary
    "cloudinary",
    "cloudinary_storage",

    # Project applications
    "core",
    "administrators",
    "sellers",
    "mails",
]


# ==========================================================
# MIDDLEWARE
# ==========================================================

MIDDLEWARE = [

    "django.middleware.security.SecurityMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",

    "django.middleware.common.CommonMiddleware",

    "django.middleware.csrf.CsrfViewMiddleware",

    "django.contrib.auth.middleware.AuthenticationMiddleware",

    "django.contrib.messages.middleware.MessageMiddleware",

    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# ==========================================================
# ROOT URL CONFIGURATION
# ==========================================================

ROOT_URLCONF = "wingastock.urls"


# ==========================================================
# TEMPLATES
# ==========================================================

TEMPLATES = [

    {
        "BACKEND":
            "django.template.backends.django.DjangoTemplates",

        "DIRS": [],

        "APP_DIRS": True,

        "OPTIONS": {

            "context_processors": [

                "django.template.context_processors.request",

                "django.contrib.auth.context_processors.auth",

                "django.contrib.messages.context_processors.messages",

            ],
        },
    },
]


# ==========================================================
# WSGI
# ==========================================================

WSGI_APPLICATION = "wingastock.wsgi.application"


# ==========================================================
# DATABASE
# ==========================================================

DATABASES = {

    "default": {

        "ENGINE":
            "django.db.backends.sqlite3",

        "NAME":
            BASE_DIR / "db.sqlite3",

    }
}


# ==========================================================
# PASSWORD VALIDATION
# ==========================================================

AUTH_PASSWORD_VALIDATORS = [

    {
        "NAME":
            "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },

    {
        "NAME":
            "django.contrib.auth.password_validation.MinimumLengthValidator",
    },

    {
        "NAME":
            "django.contrib.auth.password_validation.CommonPasswordValidator",
    },

    {
        "NAME":
            "django.contrib.auth.password_validation.NumericPasswordValidator",
    },

]


# ==========================================================
# INTERNATIONALIZATION
# ==========================================================

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# ==========================================================
# STATIC FILES
# ==========================================================

STATIC_URL = "static/"


# ==========================================================
# STATIC FILES DIRECTORY
# ==========================================================

STATICFILES_DIRS = [
    BASE_DIR / "static",
]


# ==========================================================
# CLOUDINARY CONFIGURATION
# ==========================================================

CLOUDINARY_STORAGE = {

    "CLOUD_NAME":
        os.environ.get("CLOUDINARY_CLOUD_NAME"),

    "API_KEY":
        os.environ.get("CLOUDINARY_API_KEY"),

    "API_SECRET":
        os.environ.get("CLOUDINARY_API_SECRET"),

}


# ==========================================================
# DJANGO FILE STORAGE
# ==========================================================

STORAGES = {

    # All uploaded files
    # will use Cloudinary

    "default": {

        "BACKEND":
            "cloudinary_storage.storage.MediaCloudinaryStorage",

    },


    # Static files remain local

    "staticfiles": {

        "BACKEND":
            "django.contrib.staticfiles.storage.StaticFilesStorage",

    },

}


# ==========================================================
# MEDIA
# ==========================================================

# You don't need MEDIA_ROOT for Cloudinary uploads.
#
# MEDIA_URL is also not used for Cloudinary images.
#
# Keep this only if you have other local media
# that you still need.

MEDIA_URL = "/media/"


# ==========================================================
# DEFAULT PRIMARY KEY
# ==========================================================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
