# Generated by Django 6.1 on 2026-08-30 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('supervisor_name', models.CharField(max_length=255)),
                ('supervisor_phone', models.CharField(blank=True, max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_placements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyFieldReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('activities', models.TextField(help_text='Describe the activities performed today.')),
                ('skills_learned', models.TextField(blank=True, help_text='Skills or knowledge gained today.')),
                ('challenges', models.TextField(blank=True, help_text='Challenges encountered during the day.')),
                ('solutions', models.TextField(blank=True, help_text='How the challenges were solved.')),
                ('remarks', models.TextField(blank=True)),
                ('supervisor_comment', models.TextField(blank=True)),
                ('supervisor_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='student_report.fieldplacement')),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('placement', 'date'), name='unique_daily_report_per_day')],
            },
        ),
        migrations.CreateModel(
            name='WeeklyFieldReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('summary', models.TextField(help_text='Summary of activities performed during the week.')),
                ('major_activities', models.TextField(help_text='Major activities completed during the week.')),
                ('skills_acquired', models.TextField(help_text='Skills and knowledge acquired.')),
                ('challenges', models.TextField(blank=True)),
                ('solutions', models.TextField(blank=True)),
                ('lessons_learned', models.TextField(blank=True)),
                ('plans_for_next_week', models.TextField(blank=True)),
                ('supervisor_comment', models.TextField(blank=True)),
                ('supervisor_approved', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to='student_report.fieldplacement')),
            ],
            options={
                'ordering': ['week_number'],
                'constraints': [models.UniqueConstraint(fields=('placement', 'week_number'), name='unique_weekly_report')],
            },
        ),
    ]
