# Generated by Django 6.0.6 on 2026-09-19 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedFieldReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_html', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='weeklyfieldreport',
            name='unique_weekly_report',
        ),
        migrations.AddField(
            model_name='generatedfieldreport',
            name='placement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generated_report', to='student_report.fieldplacement'),
        ),
        migrations.DeleteModel(
            name='WeeklyFieldReport',
        ),
    ]
