# Generated by Django 6.0.6 on 2026-09-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_report', '0002_generatedfieldreport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedfieldreport',
            name='google_document_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
