# Generated by Django 6.0.6 on 2026-09-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_report', '0003_generatedfieldreport_google_document_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedfieldreport',
            name='google_document_id',
        ),
        migrations.AddField(
            model_name='generatedfieldreport',
            name='summary_html',
            field=models.TextField(blank=True),
        ),
    ]
