# Generated by Django 6.0.6 on 2026-09-23 09:57

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_report', '0004_remove_generatedfieldreport_google_document_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedfieldreport',
            name='activity_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='activity image'),
        ),
        migrations.AddField(
            model_name='generatedfieldreport',
            name='appendix_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='appendix image'),
        ),
        migrations.AddField(
            model_name='generatedfieldreport',
            name='historical_background',
            field=models.TextField(blank=True, help_text='Historical background of the organization.'),
        ),
        migrations.AddField(
            model_name='generatedfieldreport',
            name='historical_background_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='historical background image'),
        ),
        migrations.AddField(
            model_name='generatedfieldreport',
            name='organization_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='organization image'),
        ),
        migrations.AddField(
            model_name='generatedfieldreport',
            name='organization_structure_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='organization structure image'),
        ),
        migrations.AddField(
            model_name='generatedfieldreport',
            name='references_bibliography',
            field=models.TextField(blank=True, help_text='References and bibliography.'),
        ),
    ]
