# Generated by Django 6.0.6 on 2026-09-24 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_report', '0005_generatedfieldreport_activity_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedfieldreport',
            name='abbreviations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='generatedfieldreport',
            name='brief_overview',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='generatedfieldreport',
            name='challenge_solutions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='generatedfieldreport',
            name='challenges',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='generatedfieldreport',
            name='conclusion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='generatedfieldreport',
            name='declaration',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='generatedfieldreport',
            name='general_observations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='generatedfieldreport',
            name='mission',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='generatedfieldreport',
            name='objectives',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='generatedfieldreport',
            name='organization_structure',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='generatedfieldreport',
            name='recommendations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='generatedfieldreport',
            name='vision',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='generatedfieldreport',
            name='historical_background',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='generatedfieldreport',
            name='references_bibliography',
            field=models.TextField(blank=True),
        ),
    ]
