# Generated by Django 6.0.6 on 2026-09-24 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_report', '0006_generatedfieldreport_abbreviations_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generatedfieldreport',
            old_name='brief_overview',
            new_name='section_21_brief_overview',
        ),
        migrations.RenameField(
            model_name='generatedfieldreport',
            old_name='challenge_solutions',
            new_name='section_22_activities_performed',
        ),
        migrations.RenameField(
            model_name='generatedfieldreport',
            old_name='challenges',
            new_name='section_23_general_observation',
        ),
        migrations.RenameField(
            model_name='generatedfieldreport',
            old_name='general_observations',
            new_name='section_24_challenges',
        ),
        migrations.RenameField(
            model_name='generatedfieldreport',
            old_name='summary_html',
            new_name='section_25_solutions',
        ),
    ]
