# Generated by Django 6.0.6 on 2026-08-31 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpinReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reward_type', models.CharField(choices=[('vocha', 'Vocha'), ('points', 'Points'), ('post_chance', 'Post Products Chance'), ('loss', 'Loss')], max_length=20)),
                ('probability', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('value', models.PositiveIntegerField(blank=True, default=0)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerSpin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spins', to=settings.AUTH_USER_MODEL)),
                ('reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.spinreward')),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
