# Generated by Django 6.0.6 on 2026-08-31 13:15

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_spinreward_customerspin_delete_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customerspin',
            name='play_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddConstraint(
            model_name='customerspin',
            constraint=models.UniqueConstraint(fields=('customer', 'play_date'), name='one_spin_per_customer_per_day'),
        ),
    ]
