# Generated by Django 6.0.6 on 2026-08-31 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customerspin_play_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerspin',
            name='reward',
            field=models.TextField(default='empty'),
        ),
        migrations.AddField(
            model_name='customerspin',
            name='points_after',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customerspin',
            name='points_before',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customerspin',
            name='points_used',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='customerspin',
            name='voucher_won',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CustomerVoucherProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='SpinReward',
        ),
    ]
