# Generated by Django 6.0.6 on 2026-08-31 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_customerspin_reward_customerspin_points_after_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerspin',
            old_name='points_after',
            new_name='points',
        ),
        migrations.RenameField(
            model_name='customerspin',
            old_name='points_before',
            new_name='reward_count',
        ),
        migrations.RemoveField(
            model_name='customerspin',
            name='points_used',
        ),
        migrations.RemoveField(
            model_name='customerspin',
            name='voucher_won',
        ),
        migrations.DeleteModel(
            name='CustomerVoucherProgress',
        ),
    ]
