# Generated by Django 6.0.6 on 2026-09-11 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliver', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryrequest',
            old_name='admin_note',
            new_name='customer_note',
        ),
    ]
