# Generated by Django 6.0.6 on 2026-08-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_remove_product_location_remove_product_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(default='saved', max_length=100),
        ),
    ]
