# Generated by Django 6.0.6 on 2026-08-26 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0005_product_comments_product_informations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_informations',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product_informations',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product_informations',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
