# Generated by Django 6.0.6 on 2026-08-26 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0006_alter_product_informations_dislikes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_informations',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_information', to='sellers.product'),
        ),
    ]
