# Generated by Django 6.0.6 on 2026-08-26 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0007_alter_product_informations_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('reaction', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellers.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('product', 'session_key'), name='unique_product_reaction_per_session')],
            },
        ),
    ]
