# Generated by Django 6.0.6 on 2026-09-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0008_productreaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('phones', 'Phones & Tablets'), ('computers', 'Computers & Laptops'), ('fashion', 'Fashion'), ('shoes', 'Shoes'), ('beauty', 'Beauty & Personal Care'), ('food', 'Food & Groceries'), ('drinks', 'Drinks & Beverages'), ('furniture', 'Furniture'), ('home', 'Home & Garden'), ('appliances', 'Home Appliances'), ('vehicles', 'Vehicles'), ('parts', 'Vehicle Parts & Accessories'), ('sports', 'Sports & Fitness'), ('books', 'Books & Education'), ('toys', 'Toys & Games'), ('baby', 'Baby & Kids'), ('services', 'Services'), ('jobs', 'Jobs'), ('property', 'Property'), ('other', 'Other')], max_length=50),
        ),
    ]
