# Generated by Django 6.0.6 on 2026-09-11 12:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0010_sellerpaymentrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='seller_dp',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='seller profile picture'),
        ),
    ]
